# Generated by Django 3.1.2 on 2020-11-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
