# Generated by Django 3.1 on 2020-09-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='user',
        ),
    ]
