# Generated by Django 3.1 on 2020-09-03 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200903_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(default=None, null=True, related_name='item', to='auctions.Auctions')),
                ('user', models.ManyToManyField(default=None, null=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
