# Generated by Django 3.1 on 2020-09-03 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200903_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_bid', to='auctions.auctions'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_comment', to='auctions.auctions'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
