# Generated by Django 3.1 on 2020-09-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='status',
        ),
        migrations.AddField(
            model_name='auctions',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
