# Generated by Django 3.1 on 2020-09-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200905_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
