# Generated by Django 3.1 on 2020-09-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bids_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
    ]
